Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2018-07, with the labels that each got.

#38 Changed all occurrences of gce- to gce-pd- when referencing the gce-pd driver
  .gitignore
  cmd/main.go
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/node.yaml
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/identity.go
  pkg/gce-pd-csi-driver/identity_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/server.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/e2e/gce_pd_e2e_test.go
  test/run-e2e-local.sh
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 Added a waitforattach verification at the end of ControllerPublishVolume
  pkg/gce-cloud-provider/fake-gce.go
  pkg/gce-cloud-provider/gce-compute.go
  pkg/gce-cloud-provider/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 Changed base image to audited Debian Base
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Add unit test runner script. Fixed some errors caught by unit tests
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/run-unit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 Lessen severity of waiting loop errors to warnings
  test/remote/remote/ssh.go
  test/remote/run_remote/run_remote.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#57 Fix for E2E test Flake
  test/remote/run_remote/run_remote.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 Added unit tests for identity server, fixed small spec inconsistency
  Dockerfile
  Makefile
  cmd/main.go
  pkg/gce-cloud-provider/gce.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/identity.go
  pkg/gce-pd-csi-driver/identity_test.go
  test/e2e/gce_pd_e2e_test.go
  test/run-e2e-local.sh
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 Use net/url library for UDS parsing, now uses more standardized form
  cmd/main.go
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/demo-pod.yaml
  deploy/kubernetes/node.yaml
  pkg/gce-pd-csi-driver/server.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/e2e/gce_pd_e2e_test.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, size/L

#58 Added controller unit tests
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/identity_test.go
  test/e2e/gce_pd_e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#59 Changed deploy yamls to prod version of container
  Makefile
  deploy/kubernetes/controller.yaml
  deploy/kubernetes/node.yaml
  pkg/gce-pd-csi-driver/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#61 Fix Makefile prod-build-container arguments
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#68 Bind GCP SA to Kubernetes Cluster-Admin for GKE
  deploy/kubernetes/deploy-driver.sh
  deploy/setup-project.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Redid test framework to bring up driver on instance and expose TCP socket with SSH Tunneling
  Makefile
  pkg/gce-pd-csi-driver/server.go
  test/binremote/archiver.go
  test/binremote/instance.go
  test/binremote/runner.go
  test/binremote/ssh.go
  test/e2e/gce_pd_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/client_wrappers.go
  test/e2e/utils/utils.go
  test/remote/remote/e2e.go
  test/remote/remote/remote.go
  test/remote/remote/ssh.go
  test/remote/remote/types.go
  test/remote/run_remote/run_remote.go
  test/run-e2e-local.sh
  test/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#73 Remove old policy bindings so that setup-project is reentrant
  deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml
  deploy/setup-project.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#74 Add detach disk permissions to custom role
  deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 Topology support
  Gopkg.lock
  Gopkg.toml
  cmd/main.go
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/metadata/fake.go
  pkg/gce-cloud-provider/metadata/metadata.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/identity.go
  pkg/gce-pd-csi-driver/identity_test.go
  pkg/gce-pd-csi-driver/node.go
  test/binremote/instance.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/client_wrappers.go
  test/e2e/utils/utils.go
  test/run-e2e-local.sh
  test/run-e2e.sh
  test/run-unit.sh
  test/sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
