Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-10, with the labels that each got.

#394 Add gke regional cluster support to k8s-integration test
  test/k8s-integration/cluster.go
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#395 Add region env for run-k8s-integration.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#396 Add Supported size range to driver info config
  test/k8s-integration/config/test-config-template.in
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#397 Bumping sidecars to latest versions for 0.6.0 staging RC
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#398 Bypass unmaintained hack/e2e.go for kubetest binary
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#399 Clean up stale testgrids from README
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#401 Use delayed binding in k8s tests
  test/k8s-integration/config/sc-standard.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#400 Bumping all images to latest versions for 0.6.0 stable release
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#405 Prefix object names to disambiguate with other CSI drivers
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#404 Move all RePD compute API calls to v1 from v1beta
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/instance.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#407 Bump resizer to v0.3.0
  README.md
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  docs/kubernetes/user-guides/resize.md
  test/k8s-integration/config/test-config-template.in
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/L

#409 Clean up all logging for the driver, log successes in all cases
  cmd/main.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/identity.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/mount-manager/device-utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#403 Add user guide for pre-provisioned volumes
  docs/kubernetes/user-guides/basic.md
  docs/kubernetes/user-guides/driver-install.md
  docs/kubernetes/user-guides/pre-provisioned.md
  examples/kubernetes/demo-pod.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#411 Make driver test capabilities configurable and remove expansion from GKE tests
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#406 Add NodeGetVolumeStats Capability/Implementation/Tests
  cmd/main.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/identity_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/node_test.go.orig
  pkg/mount-manager/fake-safe-mounter.go
  pkg/mount-manager/statter.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/client-wrappers.go
  test/sanity/sanity_test.go
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/XXL

#413 Add resizer to release staging deployments
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#414 Add test skipping based on cluster version since some tests added are fixing bugs in newer versions
  test/k8s-integration/cluster.go
  test/k8s-integration/cluster_test.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L

#418 Update CSI Spec to v1.2.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#417 Add blanket tolerations to node daemonsets
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#424 [Cherry-pick] Add test skipping based on cluster version since some tests added are fixing bugs in never versions
  test/k8s-integration/cluster.go
  test/k8s-integration/cluster_test.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L
