Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-05, with the labels that each got.

#262 Add supported filesystem types to k8s integration driver test config
  test/k8s-integration/config/test-config-template.in
Labels: approved, cncf-cla: yes, lgtm, size/XS

#266 Fix Kustomize overlay dependencies so that Dev overlay replaces driver image successfully
  Dockerfile
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#267 Only run Dynamic Provisioning tests for migration for now
  test/run-k8s-integration-migration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#264 Improve VolumeSnapshot guide
  docs/kubernetes/user-guides/snapshots.md
  examples/kubernetes/snapshot/default-volumesnapshotclass.yaml
  examples/kubernetes/snapshot/restored-pod.yaml
  examples/kubernetes/snapshot/restored-pvc.yaml
  examples/kubernetes/snapshot/snapshot.yaml
  examples/kubernetes/snapshot/source-pod.yaml
  examples/kubernetes/snapshot/source-pvc.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#268 Bump CSI Provisioner to v1.1.1 for Migration Delete fix
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 Release stable with csi-provisioner v1.1.1
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#272 Expand test focus of migration tests
  test/run-k8s-integration-migration-local.sh
  test/run-k8s-integration-migration.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#273 Bump Provisioner in staging to v1.2.0-rc1
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#275 Bump csi-provisioner to v1.2.0 for migration fixes
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 Integration with GCE cloud config
  Gopkg.lock
  cmd/main.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/token_source.go
  vendor/gopkg.in/gcfg.v1/LICENSE
  vendor/gopkg.in/gcfg.v1/doc.go
  vendor/gopkg.in/gcfg.v1/errors.go
  vendor/gopkg.in/gcfg.v1/read.go
  vendor/gopkg.in/gcfg.v1/scanner/errors.go
  vendor/gopkg.in/gcfg.v1/scanner/scanner.go
  vendor/gopkg.in/gcfg.v1/set.go
  vendor/gopkg.in/gcfg.v1/token/position.go
  vendor/gopkg.in/gcfg.v1/token/serialize.go
  vendor/gopkg.in/gcfg.v1/token/token.go
  vendor/gopkg.in/gcfg.v1/types/bool.go
  vendor/gopkg.in/gcfg.v1/types/doc.go
  vendor/gopkg.in/gcfg.v1/types/enum.go
  vendor/gopkg.in/gcfg.v1/types/int.go
  vendor/gopkg.in/gcfg.v1/types/scan.go
  vendor/gopkg.in/warnings.v0/LICENSE
  vendor/gopkg.in/warnings.v0/warnings.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#278 Bump RC overlay to contain v0.5.0 of driver rc
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#279 Release v0.5.0 version as stable
  Makefile
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
