Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-06, with the labels that each got.

#282 Update scripts to be compatible with project ids that include the org…
  deploy/kubernetes/deploy-driver.sh
  deploy/setup-project.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#280 Updating image paths to gke.gcr.io
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#285 Pull deployment scripting and RBAC rule fixes into v0.5.0 release branch
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/deploy-driver.sh
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
  deploy/setup-project.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#284 Update RBAC rules for external provisioner and attacher to the updated roles required based on upstream repositories
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#291 Change pd image placeholder in integration tests to gke.gcr.io vanity url
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#289 Remove cross validation of access modes, multiple access modes can be specified that represent all the capabilities of the volume
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#290 Cherrypick to v0.5.0: Remove cross validation of access modes, multiple access modes can be specified that represent all the capabilities of the volume
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#293 Update rc version in staging tests to validate new driver version
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#288 add ability to use gcloud to boot a gke cluster for e2e integration
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#283 Add support for raw block devices and enable block device tests on external k8s testing
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/k8s-integration/config/test-config-template.in
Labels: approved, cncf-cla: yes, lgtm, size/L

#294 Release v0.5.1 of the driver as stable
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#295 Release v0.5.1 of the driver as stable
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#297 Add 0.6.0-rc1 to staging rc test overlay
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#299 Add table for all public test status'
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#301 Give test binary the knowledge that the clusters we bring up are on cos image for test skipping
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#304 Bump external-provisioner version in staging
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#311 Create PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#312 Update CSI Sanity to v2.0.1 and fix compatibility errors
  Gopkg.lock
  Gopkg.toml
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-test/.travis.yml
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go
  vendor/github.com/kubernetes-csi/csi-test/release-tools/LICENSE
  vendor/github.com/kubernetes-csi/csi-test/utils/grpcutil.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note, size/XXL

#303 return an error if the volume ID already in use
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/mount-manager/fake-safe-mounter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#314 Cherry-Pick: GKE Integration Support into Release-0.5.X
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#318 Revert "Cherry-Pick: GKE Integration Support into Release-0.5.X"
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#320 Bump attacher to 1.2.0 in rc
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#324 Bump attacher to v1.2.0 to stable and provisioner v1.2.1
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#325 Cherry pick change to check installed kustomize version and replace with pinned version
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#322 add flag checking and temp dir utilities
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#323 Separate test k8s
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#327 bring back the handle call
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#326 move helper functions to more specific files
  test/k8s-integration/cluster.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XL

#330 update gofmt to not search unnecessary places and report files changed
  hack/update-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#329 Use new deployment strategy and version flags for k8s integration migration tests
  test/run-k8s-integration-migration-local.sh
  test/run-k8s-integration-migration.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S
