Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#361 Amend volume limits returned by the driver to documented-1 since node…
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#362 [Cherry-Pick] Amend volume limits returned by the driver to documented-1 since node boot disk is attachable disk
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#363 Bump PD version to v0.5.2-gke.0
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#370 Export kubectl path to test
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#364 Deployment spec cleanup
  README.md
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/delete-driver.sh
  deploy/kubernetes/deploy-driver.sh
  deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/rbac_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#368 Wrap all GRPC errors in status, fix semantics of NotFound errors
  Gopkg.lock
  Gopkg.toml
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/node.go
  test/sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/util.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note, size/XL

#378 Update csi-attacher to v.1.2.1 for fix to not ignore ControllerUnpublishErrors
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS
