Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-11, with the labels that each got.

#392 Add ListVolumes with PublishedNodes
  Gopkg.lock
  Gopkg.toml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/client-wrappers.go
  test/remote/instance.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#428 Remove protosanitizer.StripSecrets since the PD driver doesn't use controller or node call secrets and the StripSecrets call is expensive
  Gopkg.lock
  pkg/gce-pd-csi-driver/utils.go
  vendor/github.com/golang/protobuf/descriptor/descriptor.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/release-tools/LICENSE
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XL

#429 spelling errors
  pkg/mount-manager/fake-safe-mounter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#434 Bump snapshotter to v1.2.2 for CVE fix
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#435 Bump versions of external-resizer and external-snapshotter for CVE fix
  deploy/kubernetes/overlays/alpha/controller_add_resizer.yaml
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#436 Enable hostNetwork for workload identity
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#437 [Cherry-pick] Deploy driver with hostNetwork to fix interaction with GKE Workload Identity
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S
