Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2019-04, with the labels that each got.

#240 Set MaxVolumesPerNode in NodeGetInfo
  pkg/gce-cloud-provider/metadata/fake.go
  pkg/gce-cloud-provider/metadata/metadata.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#244 Update image locations to working ones
  README.md
  deploy/kubernetes/dev/controller.yaml
  deploy/kubernetes/stable/controller.yaml
  deploy/kubernetes/stable/node.yaml
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#246 Shapshotter to GKE Release version
  deploy/kubernetes/overlays/alpha/controller_add_snapshotter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#247 Fix stable image name
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#250 Augment script to update Kustomize if version is incorrect
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#251 Staging v1.1.0 versions of external CSI components
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 Enable topology
  deploy/kubernetes/base/setup-cluster.yaml
  deploy/kubernetes/overlays/alpha/controller_enable_topology.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/controller_enable_topology.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/controller_enable_topology.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#248 Add unit test for Node
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#252 Bump stable sidecars to v1.1.0-gke.0
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#254 Statically validate volume capabilities for CreateVolume, ControllerPublish, NodeStage, NodePublish
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#249 Use K8s external-storage test framework
  test/k8s-integration/config/sc-standard.yaml
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#256 Add feature gate setting & required test focus flag to integration tests
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#259 Make integration test kube version configurable
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 [Cherry-pick] Make integration test kube version configurable
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
