Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#619 Collect managed pd csi driver logs from node
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#620 Wait on driver deployment rather than sleep
  deploy/kubernetes/wait-for-driver.sh
  test/k8s-integration/driver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#624 Wait for windows prepull images rather than sleeping
  test/k8s-integration/main.go
  test/k8s-integration/prepull-image.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#623 Add PSP for the controller Deployment
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/base/controller/kustomization.yaml
  deploy/kubernetes/base/controller/psp.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#629 Provide a knob to run intree and csi plugin tests
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#627 Add VolumeStats for Windows
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/statter_linux.go
  pkg/mount-manager/statter_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#630 Fix ci scipt focus string
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#621 Add test support for regional PD
  test/k8s-integration/cluster.go
  test/k8s-integration/config/sc-regional.yaml
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#631 Upgrade csi sidecars to newest versions on rc
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/sidecar-upgrade.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#634 k8s-integration: Add .yaml suffix to sc-regional storageclass
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#613 Enable multi-arch build in Makefile
  Makefile
  deploy/kubernetes/base/node_windows/node.yaml
  deploy/kubernetes/images/alpha/image.yaml
  manifest_osversion.sh
  test/k8s-integration/driver.go
  test/k8s-integration/prepull.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#633 Modify NodeUnstageVolume call for Windows
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#635 Enable dump GKE node logs
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#636 Build only linux container image for tests on Linux
  test/k8s-integration/driver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#638 Use existing csi proxy client in Statter
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/mount-manager/statter_linux.go
  pkg/mount-manager/statter_windows.go
  test/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#637 Add Volume Resize support for Windows
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/resizefs/resizefs.go
  pkg/resizefs/resizefs_linux.go
  pkg/resizefs/resizefs_unsupported.go
  pkg/resizefs/resizefs_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#641 Add fstype check for Windows
  pkg/gce-pd-csi-driver/utils_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#645 Fix node version check for node skew tests
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#647 Update kustomizer to 3.8.6
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#644 Add release notes for 1.1.0 release
  CHANGELOG/CHANGELOG-1.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#652 Update staging RC to use new 1.1.0 RC build
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#648 Cherrypick #644, #647, #652 from `master` to `release-1.1`
  CHANGELOG/CHANGELOG-1.1.md
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
