Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#567 Add CSIDriver object into driver deployment script
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/csi-driver.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#570 Add metadata info in tag on PD
  deploy/kubernetes/overlays/prow-gke-release-staging-head/enable-extra-create-metadata.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#571 Skip NodeExpandVolume for block volumes
  pkg/gce-pd-csi-driver/node.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#575 Promote CSIDriver deployment to stable
  deploy/kubernetes/base/controller/csidriver_info.yaml
  deploy/kubernetes/base/controller/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/csi-driver.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#577 Promote increase timeout change to stable
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/increase-sidecar-operation-timeout.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/increase-sidecar-operation-timeout.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#415 Add support for multi-writer PD
  examples/kubernetes/demo-pod-shared-pd.yaml
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/remote/client-wrappers.go
  test/remote/instance.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#579 Move extra-create-metadata to stable
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/enable-extra-create-metadata.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#572 Update README for GA
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#580 Update stable image to v1.0.0
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/images/stable/image.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#582 Document provisioner parameters, especially fstype
  docs/kubernetes/user-guides/basic.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#562 Adding Kustomize structure in deployment README
  deploy/kubernetes/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#584 Enable Volume expansion test for GKE PDCSI driver
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#590 Project setup script authorizes GCE to use Cloud KMS keys on the dev project.
  deploy/setup-project.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/S

#586 Import the kubernetes-csi/csi-release-tools subtree.
  release-tools/.prow.sh
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/code-of-conduct.md
  release-tools/filter-junit.go
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/util.sh
  release-tools/verify-go-version.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XXL

#587 Move main to cmd/gce-pd-csi-driver, merge init-buildx.sh into Makefile.
  Dockerfile
  Dockerfile.Windows
  Makefile
  cmd/gce-pd-csi-driver/main.go
  init-buildx.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#552 Add jingxu97 to owner file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#593 Do all storage class gingko runs and report errors at the end
  test/k8s-integration/filter-junit.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#595 Strip .yaml from test output dirs
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#559 update driver test code for Windows
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/images/alpha/image.yaml
  test/k8s-integration/driver-config.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/k8s-integration/prepull-image.sh
  test/k8s-integration/prepull.yaml
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#596 Update debian base image version to 2.1.3
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#598 Cherry-pick #596 to `release-1.0` (Update debian base image version to 2.1.3)
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#597 Fix TestExtractAndDefaultParameters test.
  pkg/common/parameters_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, release-note-none, size/XS

#599 Update docs for v1.0.1 release
  CHANGELOG/CHANGELOG-1.0.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#601 Rename vendorVersion to version to comply with build.make.
  Makefile
  cmd/gce-pd-csi-driver/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#602 Cherry-pick #599 to `release-1.0` (Update docs for 1.0.1 release)
  CHANGELOG/CHANGELOG-1.0.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
