Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2020-11, with the labels that each got.

#632 Enable XFS selectively for GKE clusters with proper COS support
  test/k8s-integration/driver-config.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/L

#655 Add run-k8s-integration-ci.sh
  test/run-k8s-integration-ci.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#656 Use node version on GKE when detecting XFS compatibility
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#654 Update dev overlay so that image overwrite can work
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/noauth/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#643 Migrate from alpha to beta compute APIs
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce-compute_test.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#666 Fix check volume is mounted logic during NodePublishVolume and
  pkg/gce-pd-csi-driver/node.go
  pkg/mount-manager/safe-mounter_windows.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#661 Add disk online/offline into Stage/Unstage volumes
  deploy/kubernetes/base/node_windows/node.yaml
  go.mod
  go.sum
  pkg/mount-manager/safe-mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta2/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1beta2/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#667 Skip Pod fsgroupchange policy tests for < 1.20 k8s
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#658 Update docs/stable overlay to reference new release
  README.md
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/images/stable/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/leader-election-flag.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/volume-inuse-error-handler.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/sidecar-upgrade.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#659 Cherrypick #658 from `master` to `release-1.1`
  README.md
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/images/stable/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/leader-election-flag.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/volume-inuse-error-handler.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/sidecar-upgrade.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#669 Update csi proxy volume setup for new disk api group
  README.md
  deploy/kubernetes/base/node_windows/node.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#660 Modify integration test focus for Windows
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#671 Shorten the GKE cluster name
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#673 Add check on returned volumeIds
  pkg/mount-manager/safe-mounter_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#674 Add release notes for upcoming 1.2 release.
  CHANGELOG/CHANGELOG-1.2.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#675 Update RC image for 1.2.0 RC
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#676 Cherrypick #675 from `master` to `release-1.2`
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#677 Update docs/stable overlay images for 1.2 release
  README.md
  deploy/kubernetes/images/stable/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#678 Cherrypick #677 from `master` to `release-1.2`
  README.md
  deploy/kubernetes/images/stable/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
