Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2020-09, with the labels that each got.

#604 Use a fixed version of kustomization
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#603 e2e test should take GKE node version as an input
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#606 Remove duplicate junit results post-merge
  test/k8s-integration/filter-junit.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#609 Update driver to use csi proxy filesystem v1beta1
  deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml
  deploy/kubernetes/base/node_windows/node.yaml
  deploy/kubernetes/base/node_windows/psp.yaml
  deploy/kubernetes/images/alpha/image.yaml
  go.mod
  go.sum
  pkg/mount-manager/safe-mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1beta1/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#610 Enable usages of application default credentials
  deploy/kubernetes/deploy-driver.sh
  deploy/kubernetes/images/dev/image.yaml
  deploy/kubernetes/images/dev/kustomization.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/noauth/kustomization.yaml
  deploy/kubernetes/overlays/noauth/noauth.yaml
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/run-k8s-integration-local.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/L

#612 Update prepull image agnhost version
  test/k8s-integration/main.go
  test/k8s-integration/prepull.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
