Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#529 Add e2e CI tests for Windows
  Dockerfile.Windows
  Makefile
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/images/alpha/image.yaml
  deploy/kubernetes/overlays/alpha/kustomization.yaml
  test/k8s-integration/config/sc-windows.yaml
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#550 Add mattcary and saikat-royc as owners
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#542 Increase PD CSI sidecar operation timeout
  deploy/kubernetes/overlays/prow-gke-release-staging-head/increase-sidecar-operation-timeout.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/increase-sidecar-operation-timeout.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#555 Add MountSensitive in CSIproxy mounter
  Makefile
  hack/verify-all.sh
  pkg/mount-manager/safe-mounter_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#551 Update CI test configuration
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#556 Update windows test script
  init-buildx.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#563 Fix Random CMEK Disk Creation Failure (disk already exists)
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce-compute_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L
