Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#688 Use v0.7.0 image for release-0.7
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#691 Windows Server 20H2 and 2004 support, configurable base layer versions.
  Dockerfile.Windows
  Makefile
  manifest_osversion.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/M

#692 Automated cherry pick of #691: Add Windows 2004 and 20H2 support and ability to specify a
  Dockerfile.Windows
  Makefile
  manifest_osversion.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#696 Add logs for Windows pod for debugging
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#697 Fix issue for taint linux nodes for Windows tests
  test/k8s-integration/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#698 Staging RC overlay: Bump all sidecar versions to latest
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/controller_patches.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#699 Stable overlay - bump all sidecar versions to latest
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/stable/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/controller_patches.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L
