Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#700 Update prepull image version
  test/k8s-integration/prepull.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#702 Disable controller service on nodes
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/base/node_windows/node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#703 Fix the kustomize version
  deploy/kubernetes/install-kustomize.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#705 Remove csi-driver-registrar flag
  deploy/kubernetes/base/node_windows/node.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#704 Add new per k8s minor version overlays
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-15/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-15/kustomization.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/kustomization.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/kustomization.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/kustomization.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/kustomization.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/kustomization.yaml
  deploy/kubernetes/images/stable-1-15/image.yaml
  deploy/kubernetes/images/stable-1-15/kustomization.yaml
  deploy/kubernetes/images/stable-1-16/image.yaml
  deploy/kubernetes/images/stable-1-16/kustomization.yaml
  deploy/kubernetes/images/stable-1-17/image.yaml
  deploy/kubernetes/images/stable-1-17/kustomization.yaml
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-18/kustomization.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-1-19/kustomization.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  deploy/kubernetes/images/stable-master/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-15/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-15/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-16/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-16/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-17/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-17/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/README.md
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-15/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-15/metrics_leaderelection_endpoint.yaml
  deploy/kubernetes/overlays/stable-1-15/no_resizer_snapshotter_roles.yaml
  deploy/kubernetes/overlays/stable-1-15/no_resizer_snapshotter_sidecar.yaml
  deploy/kubernetes/overlays/stable-1-15/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-1-16/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-16/metrics_leaderelection_endpoint.yaml
  deploy/kubernetes/overlays/stable-1-16/no_snapshotter_roles.yaml
  deploy/kubernetes/overlays/stable-1-16/no_snapshotter_sidecar.yaml
  deploy/kubernetes/overlays/stable-1-16/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-1-17/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-17/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-1-18/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-18/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-1-19/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-19/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-master/kustomization.yaml
  deploy/kubernetes/overlays/stable-master/no_win_roles.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#707 Add pdcsi Windows migration test script
  test/run-k8s-windows-migration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#706 Add hack/verify-coverage.sh
  hack/verify-coverage.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#693 Allow to label PD disk with k8s cluster ID
  cmd/gce-pd-csi-driver/main.go
  go.mod
  go.sum
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/identity_test.go
  pkg/gce-pd-csi-driver/node_test.go
  test/sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/disk/v1beta1/client_generated.go
  vendor/k8s.io/component-base/LICENSE
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
  vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go
  vendor/k8s.io/component-base/cli/flag/configuration_map.go
  vendor/k8s.io/component-base/cli/flag/flags.go
  vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go
  vendor/k8s.io/component-base/cli/flag/map_string_bool.go
  vendor/k8s.io/component-base/cli/flag/map_string_string.go
  vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
  vendor/k8s.io/component-base/cli/flag/noop.go
  vendor/k8s.io/component-base/cli/flag/omitempty.go
  vendor/k8s.io/component-base/cli/flag/sectioned.go
  vendor/k8s.io/component-base/cli/flag/string_flag.go
  vendor/k8s.io/component-base/cli/flag/tristate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XXL

#708 Documentation for overlays (part 1)
  docs/release/overlays.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#710 Enable windows driver components for k8s minor staging overlays
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#711 Fix issues in Windows migration test
  test/k8s-integration/main.go
  test/run-k8s-windows-migration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#689 Add usage of regiona PD in zonal clusters to user guide
  docs/kubernetes/user-guides/basic.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#682 Remove Probe logging
  pkg/gce-pd-csi-driver/utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#713 Add Windows jobs for stable-1.18, 1.19 and master
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-18/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-1-19/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-18/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-18/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-1-19/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-19/no_win_roles.yaml
  deploy/kubernetes/overlays/stable-master/kustomization.yaml
  deploy/kubernetes/overlays/stable-master/no_win_roles.yaml
  test/run-k8s-windows-migration.sh
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#714 Switch the integration scripts and deploy driver scripts default overlays
  deploy/kubernetes/README.md
  deploy/kubernetes/delete-driver.sh
  deploy/kubernetes/deploy-driver.sh
  deploy/kubernetes/images/alpha/kustomization.yaml
  deploy/kubernetes/overlays/prow-gke-release-staging-head/kustomization.yaml
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration-migration.sh
  test/run-k8s-integration.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#712 Add a mode to run e2e tests using kubetest2.
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration-migration.sh
  test/run-k8s-integration.sh
  test/run-k8s-windows-migration.sh
  test/run-windows-k8s-integration.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#715 Update README for overlays
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M
