Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2021-07, with the labels that each got.

#796 Rename master to main
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#799 update documentation to show that any PD disk type can be used
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#801 CHANGELOG-1.3
  CHANGELOG/CHANGELOG-1.3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#800 add link to release doc
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#802 stage v1.3.0-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#803 fix image repo
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#805 Fix kubectl parsing
  test/k8s-integration/cluster.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#804 release-1.3 cut details
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/XS

#807 release-1.3 cut details
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
