Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2021-09, with the labels that each got.

#829 Update base image to buster-v1.9.0
  Dockerfile
  deploy/kubernetes/install-kustomize.sh
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter_linux.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_windows.go
  pkg/resizefs/resizefs_linux.go
  pkg/resizefs/resizefs_unsupported.go
  test/k8s-integration/.dockerized-kube-version-defs
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/run-k8s-integration.sh
Labels: kind/bug, cncf-cla: yes, approved, release-note, size/M

#831 v1.0.2 release notes
  CHANGELOG/CHANGELOG-1.0.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#832 Add legacy build directives necessary for some go versions
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter_linux.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_windows.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#833 1.0.3 notes
  CHANGELOG/CHANGELOG-1.0.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#834 v1.0.4 notes
  CHANGELOG/CHANGELOG-1.0.md
Labels: cncf-cla: yes, approved, size/XS, release-note-none

#836 replace gcr.io/gke-release-staging to use k8s.gcr.io/cloud-provider-gcp
  deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-15/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#837 add test skip for Generic Ephemeral Volume tests
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none, ok-to-test

#838 Cherry pick #788 to release-1.2
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter_linux.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_windows.go
  pkg/resizefs/resizefs_linux.go
  pkg/resizefs/resizefs_windows.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#839 Update debian images to buster-v1.9.0
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#840 changelog for v1.2.3
  CHANGELOG/CHANGELOG-1.2.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#841 Update buster version to 1.9.0
  Dockerfile
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/mount-manager/safe-mounter-v1_windows.go
  pkg/mount-manager/safe-mounter-v1beta_windows.go
  pkg/mount-manager/safe-mounter_linux.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_windows.go
  pkg/resizefs/resizefs_linux.go
  pkg/resizefs/resizefs_windows.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S

#842 Changelog for 1.3.2
  CHANGELOG/CHANGELOG-1.3.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#845 Really correct staging image for 1.3.2-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none
