Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#1090 added labels for namespace and pvc names for a pv
  pkg/common/parameters.go
  pkg/common/parameters_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#1094 Disable per volume backoff behavior for sanity tests
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, tide/merge-method-squash, ok-to-test

#1095 Automated cherry pick of #1072: Add udevadm to container image
  Dockerfile
Labels: cncf-cla: yes, approved, release-note, size/XS

#1097 Automated cherry pick of #1072: Add udevadm to container image
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1098 Fix micro > milli max backoff bug
  cmd/gce-pd-csi-driver/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1100 Remove labels from test snapshot class
  test/k8s-integration/config/image-volumesnapshotclass.yaml
  test/k8s-integration/config/pd-volumesnapshotclass.yaml
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1079 Add provisionedIops for pd-extreme
  README.md
  go.mod
  go.sum
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/tests/single_zone_pd_extreme_e2e_test.go
  test/k8s-integration/config/sc-extreme.yaml
  test/k8s-integration/driver-config.go
  vendor/k8s.io/cloud-provider/LICENSE
  vendor/k8s.io/cloud-provider/volume/constants.go
  vendor/k8s.io/cloud-provider/volume/helpers/rounding.go
  vendor/k8s.io/cloud-provider/volume/helpers/zones.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test

#1092 Separate user errors from internal errors
  cmd/gce-pd-csi-driver/main.go
  pkg/deviceutils/device-utils.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/metadata/metadata.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/server.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_test.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/metrics/metrics.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_linux.go
  test/k8s-integration/cluster.go
  test/remote/ssh.go
  test/sanity/sanity_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note-none, size/XL, ok-to-test

#1041 Fix incorrect example in installation README
  docs/kubernetes/user-guides/driver-install.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none, ok-to-test

#1103 Update go version to the latest
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1104 Automated cherry pick of #1103: Update go version to the latest
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1105 release-1.7: Update golang to 1.18.9
  Dockerfile
  Dockerfile.Windows
Labels: cncf-cla: yes, approved, release-note, size/XS, kind/cleanup
