Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2022-05, with the labels that each got.

#963 Add functionality to make architecture specific builds
  Makefile
  test/e2e/tests/setup_e2e_test.go
  test/remote/archiver.go
  test/remote/instance.go
  test/remote/setup-teardown.go
  test/run-e2e-local.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none, ok-to-test

#966 Run snapshot class tests separately from other tests
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
  test/run-k8s-integration-ci.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/failing-test, release-note-none

#973 Increase prepull image timeout
  Makefile
  test/k8s-integration/prepull-image.sh
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#974 Add runtime libraries necessary for sed (dependency of lib/udev_conta…
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#980 Add Changelog for v1.6.0
  CHANGELOG/CHANGELOG-1.6.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none, ok-to-test

#981 only skip cloning tests, not all snapshot tests
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#983 Debugging statement to check the transformed manifest
  manifest_osversion.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#984 really fix pvc.data.source skip
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#993 fix 1.22 and 1.23 image repositories
  deploy/kubernetes/images/stable-1-22/image.yaml
  deploy/kubernetes/images/stable-1-23/image.yaml
  deploy/kubernetes/overlays/stable-1-22/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#988 Simplify node backoff logic for controller publish/unpublish op
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XL

#994 CHANGELOG for 1.7
  CHANGELOG/CHANGELOG-1.7.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, release-note, size/M

#995 Cherry-pick release v1.6.0 changelog to master, with note about bug
  CHANGELOG/CHANGELOG-1.6.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#996 Discourage 1.6 branch
  CHANGELOG/CHANGELOG-1.6.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#997 update prow rc image with 1.7.0-rc1 candidate
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#986 Remove workaround to add os.version to the manifest for Windows images
  manifest_osversion.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1002 Automated cherry pick of #986: Remove workaround to add os.version to the manifest for
  manifest_osversion.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test
