Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2022-02, with the labels that each got.

#906 Add missing --migration-test=true flag
  test/run-windows-k8s-migration.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#909 use cos_containerd as default image
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#912 Bump buster version and make 1.3.5
  CHANGELOG/CHANGELOG-1.3.md
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#911 Bump debian image for 1.2 release.
  CHANGELOG/CHANGELOG-1.2.md
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#916 Pull v1.2.5 and v1.3.5 changelog to master
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#919 Remove verult from OWNERS files
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, triage/accepted
