Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2022-01, with the labels that each got.

#876 Add guest-configs to go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#879 Add CREATE_SA_KEY flag to deploy/setup-project.sh
  deploy/setup-project.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none, ok-to-test

#884 add back in copy from mad-hack version for arm64
  Dockerfile.arm64
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#885 Cherry pick #884 to release-1.4
  Dockerfile.arm64
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none, ok-to-test

#886 Move readonly from dev to base
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  deploy/kubernetes/overlays/dev/controller_readonly.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#887 Cherry Pick #886 [Move readonly from dev to base] to release-1.4
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  deploy/kubernetes/overlays/dev/controller_readonly.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#888 stage v1.4.0-rc2
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, ok-to-test

#889 Cherry pick stage v1.4.0-rc2 #888 to release 1.4
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, ok-to-test

#893 Use the compiled kubernetes binaries in the e2e tests in CI
  test/k8s-integration/fs.go
  test/k8s-integration/main.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note-none

#896 Fix repo
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#897 Cherry pick Fix repo #896 to release-1.4
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#900 add nvme script and rules as static files
  Dockerfile
  deploy/kubernetes/README.md
  deploy/kubernetes/udev/README
  deploy/kubernetes/udev/google_nvme_id
  deploy/kubernetes/update-nvme.sh
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note-none, ok-to-test

#899 Unify the build/test strategy of OSS GCE PD CSI Driver for Linux and Windows
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration.sh
  test/run-windows-k8s-integration.sh
  test/run-windows-k8s-migration.sh
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, kind/cleanup, release-note-none

#901 Add missing unbound variable teardown_driver
  test/run-windows-k8s-integration.sh
  test/run-windows-k8s-migration.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#902 Add missing backlash in run-windows-k8s-migration.sh
  test/run-windows-k8s-migration.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#903 Run the k8s-integration-test binary without eval
  test/run-windows-k8s-integration.sh
  test/run-windows-k8s-migration.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S, release-note-none

#904 Use double quotes to expand variables in the windows migration e2e script
  test/run-windows-k8s-integration.sh
  test/run-windows-k8s-migration.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/M, release-note-none

#907 v1.4.0 image and readme
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none
