Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#1022 Backport maxprocs (#969)
  cmd/gce-pd-csi-driver/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1024 Pin kubetest2 version
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration-migration.sh
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/failing-test, release-note-none

#1015 update stable master and README reference to 1.7.2
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1028 backoff per {node,disk} pair instead of just node}
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#975 Remove livenessprobe from node-driver-registrar
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/base/node_windows/node.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#1017 add support for setting snapshot labels
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#1030 Skip node skew tests using ephemeral containers
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1031 update go builder to 1.18.4
  Dockerfile
Labels: cncf-cla: yes, approved, release-note, size/XS, kind/cleanup

#1032 Cherry-pick #1031: update go to 1.18
  Dockerfile
Labels: cncf-cla: yes, approved, release-note, size/XS, kind/cleanup

#1033 Update golang and base image
  Dockerfile
Labels: cncf-cla: yes, approved, release-note, size/XS, kind/cleanup

#1034 Point changelog to master branch
  CHANGELOG/README.md
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, release-note-none

#1036 backoff per {node,disk} pair instead of just node}
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
Labels: kind/bug, size/L, cncf-cla: yes, approved, release-note
