Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#1466 Update changelog
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: size/L, cncf-cla: yes, approved, release-note

#1485 Update nvme /dev/ device search path to only identify drive/namespace paths
  go.mod
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XL

#1493 add songjiaxun to owners
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1488 [release-1.11] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify
  go.mod
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, release-note, size/XL

#1487 [release-1.12] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify
  go.mod
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL

#1507 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1506 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1505 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1504 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1503 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1502 Bump Golang Builder version to 1.20.11
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1497 Bump google.golang.org/grpc to fix CVE-2023-44487
  go.mod
  go.sum
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/idle.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/observability.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/serviceconfig/duration.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, size/XXL, release-note, ok-to-test

#1492 Bump google.golang.org/grpc to fix CVE-2023-44487
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#1491 Bump google.golang.org/grpc to fix CVE-2023-44487
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, release-note, size/M, ok-to-test

#1285 chore: remove refs to deprecated io/ioutil
  pkg/gce-pd-csi-driver/node_test.go
  release-tools/filter-junit.go
  test/k8s-integration/filter-junit.go
  test/k8s-integration/utils.go
  test/remote/archiver.go
  test/remote/instance.go
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none, ok-to-test

#1508 update CHANGELOG
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none, size/XL

#1514 Add error logging when error is encountered fetching a VolumeSnapshotContent source image
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#1524 Use GCE Alpha API to create zonal disks when Storage Pools is enabled
  pkg/common/parameters.go
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1414 Fix Kubernetes Integration test status icon
  README.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none
