Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#1244 Automated cherry pick of #1150: fix bug where volume cloning topology requirements are #1232: Use errors.As so we can detect wrapped errors, and check for #1227: Adding new metric pdcsi_operation_errors to fetch error
  cmd/gce-pd-csi-driver/main.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  pkg/metrics/metrics.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/instance.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test

#1245 Update debian base image to latest version for CVE fixes
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1252 Remove nouid32 which breaks xfs
  test/k8s-integration/config/test-config-template.in
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1253 Use noatime as test mount option
  test/k8s-integration/config/test-config-template.in
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1255 Filter out user errors from GetDisk error returned from ControllerPublishVolume
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1254 Add force attach to storage class
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/remote/client-wrappers.go
  test/run-e2e-local.sh
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/XL

#1258 fix flaky node-skew tests by disabling node autoupgrade
  test/k8s-integration/cluster.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1260 Use v1.10.3 as RC
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1262 Remove updating disk type for existing disks
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup, ok-to-test

#1264 Update go version to 1.20.5 to address CVE fixes
  Dockerfile
Labels: cncf-cla: yes, approved, release-note, size/XS, kind/cleanup

#1270 update Dockerfile.windows go version to 1.20.5
  Dockerfile.Windows
Labels: cncf-cla: yes, approved, release-note, size/XS

#1271 [release-1.8] update go version to 1.19.10
  Dockerfile
  Dockerfile.Windows
Labels: cncf-cla: yes, approved, release-note, size/XS

#1272 [release-1.10] Update Docker.Windows to 1.20.5
  Dockerfile.Windows
Labels: cncf-cla: yes, approved, release-note, size/XS

#1224 Automated cherry pick of #1212: Rewrite PD CSI error message when encountering diskType
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1259 v1.10.3 release notes
  CHANGELOG/CHANGELOG-1.10.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1278 Fix provisioned-iops-on-create passing logic
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#1284 [release-1.8] Fix provisioned-iops-on-create passing logic
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/tests/single_zone_pd_extreme_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1283 [release-1.9]Fix provisioned-iops-on-create passing logic
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1281 Add Changelog for 1.10.4
  CHANGELOG/CHANGELOG-1.10.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none, tide/merge-method-squash

#1276 Add Changelog for 1.8.7
  CHANGELOG/CHANGELOG-1.8.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none, tide/merge-method-squash

#1275 Add Changelog for 1.7.9
  CHANGELOG/CHANGELOG-1.7.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none, tide/merge-method-squash

#1287 emit metrics even for success scenarios
  pkg/gce-pd-csi-driver/controller.go
  pkg/metrics/metrics.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test
