Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#1180 Update go version to 1.20
  Dockerfile
  go.mod
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup, ok-to-test

#1184 add changelog for 1.10
  CHANGELOG/CHANGELOG-1.10.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none

#1189 Skip snapshot and restore test
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1186 Automated cherry pick of #1162: Fix for CVEs #1158: go version updates
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1188 Automated cherry pick of #1162: Fix for CVEs #1158: go version updates
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/node_test.go
  test/k8s-integration/main.go
  test/k8s-integration/version.go
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1192 add changelog for 1.8.3
  CHANGELOG/CHANGELOG-1.8.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1194 release-1.10 cut details for v1.10.0
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1195 add changelog for 1.7.5
  CHANGELOG/CHANGELOG-1.7.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1200 Add sunnylovestiramisu as reviewer and approver
  OWNERS
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#1198 Update changelog for 1.7.6, and update prow-stable-sidecar-rc image
  CHANGELOG/CHANGELOG-1.7.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1199 Update changelog for 1.8.4, and update prow-stable-sidecar-rc image
  CHANGELOG/CHANGELOG-1.8.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1202 Add changelog for 1.9.3
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/M, release-note-none

#1151 Update registry k8s.gcr.io -> registry.k8s.io
  Dockerfile.debug
  README.md
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/base/node_windows/node.yaml
  deploy/kubernetes/images/prow-canary-sidecar/image.yaml
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/images/stable-1-21/image.yaml
  deploy/kubernetes/images/stable-1-22/image.yaml
  deploy/kubernetes/images/stable-1-23/image.yaml
  deploy/kubernetes/images/stable-1-24/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  docs/kubernetes/user-guides/snapshots.md
  examples/kubernetes/demo-windows.yaml
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#1205 Update go version and base image url in Dockerfile.debug and windows
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup, ok-to-test

#1204 add libbsd and libmd
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS, ok-to-test

#1206 Add xfs storageclass to enable xfs volumeexpansion tests
  test/k8s-integration/config/sc-xfs.yaml
  test/run-k8s-integration-ci.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none

#1207 Automated cherry pick of #1204: add libbsd and libmd
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1208 Automated cherry pick of #1204: add libbsd and libmd
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1209 Automated cherry pick of #1204: add libbsd and libmd
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1210 Automated cherry pick of #1204: add libbsd and libmd
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#1211 Add changelog for 1.10.1, 1.9.4, 1.8.5, 1.7.7
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1213 Update docs and stable image to reference new release 1.10.1
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#1214 Skip mount options test until we fix the invalid mount options for xfs
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none
