Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#1526 Validate storage pools in CreateVolume
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/XL

#1534 add enable_storage_pools label to OperationErrorMetric
  pkg/gce-pd-csi-driver/controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1536 [release-1.12] Update golang builder to 1.20.12
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1532 Add --fallback-requisite-zones command line argument
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/sanity/sanity_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1545 [release-1.10] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify
  go.mod
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL

#1544 Increase strictness of fully qualified GCP link cleaning in e2e test parsing code
  test/e2e/tests/single_zone_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1546 Add changelogs for latest patch releases
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  hack/generate-patch-release-notes.sh
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none

#1557 Add changelog for 1.12.6, 1.11.8, 1.10.13, 1.9.15, 1.7.20
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none
