Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#1396 Add tyuchn to owner and reviewer list
  OWNERS
Labels: cncf-cla: yes, release-note, size/XS

#1382 Update changelog for release v1.8.11, v1.7.13
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1378 1.12 CHANGELOG, update rc image
  CHANGELOG/CHANGLOG-1.12.MD
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, release-note, size/S

#1406 Change Unavailable error codes that signal a problem with the driver to Internal error codes.
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/identity.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1408 Automated cherry pick of #1406: Change Unavailable error codes that signal a problem with the
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/identity.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1405 Bump go version to 1.20.8 in release-1.7
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1404 Bump go version to 1.20.8 in release-1.8
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1413 Initialize flags prior to setting --logtostderr in test/k8s-integration/main.go
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1412 Update go version to 1.20.9
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS, ok-to-test

#1410 Update changelog for release v1.7.15, v1.8.14, v1.9.10, v1.10.8, v1.11.2, and v1.12.0
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, kind/documentation, approved, release-note, size/M

#1407 Update mentions of testgrid dashboard link
  docs/release/overlays.md
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none, ok-to-test

#1449 Add Groups in Dependabot for the Rest Dependencies
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#1453 Bump go version to 1.20.10
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1467 Change DisableDevice error to warning
  pkg/gce-pd-csi-driver/node.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1477 Automated cherry pick of #1338: Always call LoggedError for errors returned from
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, size/S, release-note-none

#1478 Automated cherry pick of #1338: Always call LoggedError for errors returned from
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, size/S, release-note-none
