Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#1368 Add missing CHANGELOG
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1369 Build and publish arm64 images
  Makefile
  README.md
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1333 Updating changelog for release v1.11.0, v1.10.6, v1.9.8, v1.8.9 v1.7.11
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none, size/XL

#1370 Add the arm64 image to the manifest create command
  CHANGELOG/README.md
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1371 Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address https://github.com/grpc/grpc-go/issues/6373
  go.mod
  go.sum
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#1365 Update changelog for release v1.11.1, v1.10.7, v1.9.9, v1.8.10, v1.7.12
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/M, release-note-none

#1373 Upgrade google.golang.org/grpc from v1.55.0 -> v1.55.1 to address grpc/grpc-go#6373
  go.mod
  go.sum
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#1374 Update overlay to test latest 1.8 rc release
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, size/XS, release-note-none

#1379 Remove ARG BUILDPLATFORM from Dockerfile
  Dockerfile
  Dockerfile.Windows
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1389 Remove ARG BUILDPLATFORM from Dockerfile
  Dockerfile
  Dockerfile.Windows
Labels: cncf-cla: yes, lgtm, release-note, size/XS

#1327 [release-1.8] Automated cherry pick of #1298: Use original error code when backing off
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1383 Bump go version to 1.20.8 to fix CVE
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS
