Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#1110 Clean up error logging in test
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/cluster.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/remote/archiver.go
  test/remote/client-wrappers.go
  test/remote/instance.go
  test/remote/runner.go
  test/remote/setup-teardown.go
  test/remote/ssh.go
Labels: size/L, cncf-cla: yes, lgtm, approved, kind/cleanup, release-note-none

#1111 cherry pick #1085 #1087 and #1094 to release-1.8
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/utils.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1113 Build binary by statically linking go
  Makefile
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, ok-to-test

#1114 Document edge cases for local e2e tests
  docs/kubernetes/development.md
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none, ok-to-test

#1115 Automated cherry pick of #1073: Add debugging log for the mapping of a PD name to /dev/* path #1084: Upgrade klog v1 to v2 and fix error wrapping #1092: Separate user errors from internal errors
  cmd/gce-pd-csi-driver/main.go
  go.mod
  go.sum
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/metadata/metadata.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/server.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_test.go
  pkg/gce-pd-csi-driver/utils_windows.go
  pkg/metrics/metrics.go
  pkg/mount-manager/device-utils.go
  pkg/mount-manager/safe-mounter-v1_windows.go
  pkg/mount-manager/safe-mounter-v1beta_windows.go
  pkg/mount-manager/safe-mounter_windows.go
  pkg/mount-manager/statter_linux.go
  pkg/resizefs/resizefs_linux.go
  pkg/resizefs/resizefs_windows.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/cluster.go
  test/k8s-integration/driver.go
  test/k8s-integration/filter-junit.go
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
  test/k8s-integration/version.go
  test/remote/archiver.go
  test/remote/client-wrappers.go
  test/remote/instance.go
  test/remote/runner.go
  test/remote/setup-teardown.go
  test/remote/ssh.go
  test/sanity/sanity_test.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note-none

#1116 Update changelog and prow tag
  CHANGELOG/CHANGELOG-1.8.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none, ok-to-test

#1121 Migrate away from google.com gcp project k8s-testimages
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#1119 Fix kms permissions for local e2e tests
  deploy/setup-project.sh
  docs/kubernetes/development.md
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/cleanup, release-note-none, ok-to-test

#1109 Succeed unpublish when a zonal, underspecified PD is not found
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/tests/single_zone_pd_extreme_e2e_test.go
  test/remote/instance.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note-none, size/XL, ok-to-test

#1122 Update readme and stable image
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test
