Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#1261 Filter out GCE operation error codes caused by user errors
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce-compute_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1294 Add option to serialize formatAndMount
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  test/e2e/utils/utils.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1298 Use original error code when backing off
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, kind/cleanup

#1304 Replace cleanSelfLink with getResourceId
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1308 Cherry-pick #1304 to release-1.9
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1306 Increase parallelism in e2e test
  test/e2e/utils/utils.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1313 Cherrypick #1294
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  test/e2e/utils/utils.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1316 Update CHANGELOG for 1.8, 1.9 and 1.10; update rc image versions
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, approved, size/M, release-note-none

#1317 Add change log for v1.7.10
  CHANGELOG/CHANGELOG-1.7.md
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none
