Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#1320 Change e2e test machine type to n2-standard-2 to include more Hyperdisk cases
  test/e2e/tests/setup_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1326 Automated cherry pick of #1232: Use errors.As so we can detect wrapped errors, and check for
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  test/remote/instance.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1330 Update go version to 1.20.6 to fix CVE
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS, ok-to-test

#1331 [release-1.10] Automated cherry pick of #1330: Update go version to 1.20.6 to fix CVE
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1332 [release-1.9] Automated cherry pick of #1330: Update go version to 1.20.6 to fix CVE
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1335 Update go version to 1.19.11 to fix CVE-2023-29406
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS, ok-to-test

#1338 Always call LoggedError for errors returned from CloudProvider methods
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#1336 Update go version to 1.19.11 to fix CVE-2023-29406
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS, ok-to-test

#1339 Fix zone specification in HdT tests
  test/e2e/tests/single_zone_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, kind/failing-test, size/XS

#1337 Update test/run-e2e.sh to match PROW configuration
  test/run-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, kind/flake

#1342 Use precompiled stable release of Kubernetes by default when running integration test
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/k8s-integration/version.go
  test/run-k8s-integration.sh
Labels: size/L, cncf-cla: yes, lgtm, approved, kind/cleanup, release-note-none

#1346 Update go version to 1.20.7 to fix CVEs
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, release-note, size/XS, ok-to-test

#1347 [release-1.11] Update go version to 1.20.7 to fix CVEs
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1309 Add pd-extreme e2e test case of defaulting to default iops when iops not set
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, kind/cleanup

#1350 [release-1.8]Update go version to 1.19.12 to fix CVEs
  Dockerfile
  Dockerfile.Windows
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1251 Delete stable overlays and update docs with recommended versions.
  README.md
  deploy/kubernetes/images/stable-1-21/image.yaml
  deploy/kubernetes/images/stable-1-21/kustomization.yaml
  deploy/kubernetes/images/stable-1-22/image.yaml
  deploy/kubernetes/images/stable-1-22/kustomization.yaml
  deploy/kubernetes/images/stable-1-23/image.yaml
  deploy/kubernetes/images/stable-1-23/kustomization.yaml
  deploy/kubernetes/images/stable-1-24/image.yaml
  deploy/kubernetes/images/stable-1-24/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-21/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-21/psp_controller.yaml
  deploy/kubernetes/overlays/stable-1-21/psp_linux.yaml
  deploy/kubernetes/overlays/stable-1-21/psp_windows.yaml
  deploy/kubernetes/overlays/stable-1-22/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-22/psp_controller.yaml
  deploy/kubernetes/overlays/stable-1-22/psp_linux.yaml
  deploy/kubernetes/overlays/stable-1-22/psp_windows.yaml
  deploy/kubernetes/overlays/stable-1-23/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-23/psp_controller.yaml
  deploy/kubernetes/overlays/stable-1-23/psp_linux.yaml
  deploy/kubernetes/overlays/stable-1-23/psp_windows.yaml
  deploy/kubernetes/overlays/stable-1-24/kustomization.yaml
  deploy/kubernetes/overlays/stable-1-24/psp_controller.yaml
  deploy/kubernetes/overlays/stable-1-24/psp_linux.yaml
  deploy/kubernetes/overlays/stable-1-24/psp_windows.yaml
  docs/release/overlays.md
Labels: cncf-cla: yes, lgtm, approved, kind/cleanup, release-note-none, size/XL

#1352 Add option to serialize formatAndMount
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils_linux.go
  pkg/gce-pd-csi-driver/utils_windows.go
  test/e2e/utils/utils.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1354 Add pwschuurman as reviewer/approver to gcp-compute-persistent-disk-csi-driver repository
  OWNERS
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#1355 Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1359 Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1356 Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1357 Automated cherry pick of #1354: Add pwschuurman as reviewer/approver to
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none
