Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#1854 1.15.2 update rc image
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1861 Automated cherry pick of #1826: Add ControllerModifyVolume E2E tests #1836: Create documentation for ControllerModifyVolume and controller default #1838: Enable VolumeAttributesClass feature gate for CI runs #1841: Update logic to use SI for VACs
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/overlays/dev/driver-args.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  docs/kubernetes/user-guides/volume-attributes-class.md
  examples/kubernetes/demo-vol-create.yaml
  examples/kubernetes/demo-vol-update.yaml
  examples/kubernetes/demo-vol-update.yml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
  test/run-e2e.sh
  test/run-k8s-integration-ci.sh
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#1862 1.15.2-rc2 update rc image
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1869 Revert "Automated cherry pick of #1826: Add ControllerModifyVolume E2E tests#1836: Create documentation for ControllerModifyVolume and controller default#1838: Enable VolumeAttributesClass feature gate for CI runs#1841: Update logic to use SI for VACs"
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/overlays/dev/driver-args.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  docs/kubernetes/user-guides/volume-attributes-class.md
  examples/kubernetes/demo-vol-create.yaml
  examples/kubernetes/demo-vol-update.yaml
  examples/kubernetes/demo-vol-update.yml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
  test/run-e2e.sh
  test/run-k8s-integration-ci.sh
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none, ok-to-test

#1870 Revert "Update logic to use SI for VACs"
  deploy/kubernetes/overlays/dev/driver-args.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  examples/kubernetes/demo-vol-create.yaml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none, ok-to-test

#1871 Update release candidate image to 1.15.2-rc3
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, ok-to-test

#1878 Update ./hack/verify-docker-deps.sh script to validate dependencies on build platform
  Dockerfile
  Makefile
  hack/print-missing-deps.sh
  hack/verify-docker-deps.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/failing-test, release-note-none

#1879 Remove make from verify-all in order to reduce presubmit flakes
  hack/verify-all.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1877 Update change log
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  CHANGELOG/CHANGELOG-1.15.md
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none
