Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#1559 Filter multiattach errors
  pkg/common/utils.go
  pkg/common/utils_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#1558 change GetDisk error reporting to temporary in CreateVolume codepath
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1563 Add command line flag for enabling Storage Pools feature
  cmd/gce-pd-csi-driver/main.go
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/sanity/sanity_test.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1571 prune changelog for 1.13
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, size/XXL, kind/documentation, approved, release-note-none

#1572 release 1.13 testing and changelog
  CHANGELOG/CHANGELOG-1.13.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: size/L, cncf-cla: yes, kind/documentation, approved, release-note-none, kind/test

#1573 Release 1.13 doc and image update
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, kind/documentation, approved, size/S, release-note-none

#1574 Add changelog for 1.12.7
  CHANGELOG/CHANGELOG-1.12.md
Labels: cncf-cla: yes, kind/documentation, approved, size/S, release-note-none

#1581 [release-1.8] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify
  go.mod
  pkg/mount-manager/device-utils.go
  pkg/mount-manager/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL

#1580 [release-1.9] Automated cherry pick of #1485: Update nvme /dev/ device search path to only identify
  go.mod
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL

#1582 v1.9.16 and v1.8.19 Changelog
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, kind/documentation, approved, size/M, release-note-none

#1579 update klog version to latest. change %w unwrap to %v
  go.mod
  go.sum
  pkg/gce-pd-csi-driver/node.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/filter-junit.go
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
  test/remote/instance.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/context.go
  vendor/github.com/go-logr/logr/context_noslog.go
  vendor/github.com/go-logr/logr/context_slog.go
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/funcr/slogsink.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr.go
  vendor/github.com/go-logr/logr/slogsink.go
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/contextual_slog.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/klog/v2/safeptr.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note, kind/cleanup
