Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#1845 Automated cherry pick of #1658: Add support for checking if a device is being used by a filesystem
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_linux.go
  pkg/deviceutils/device-utils_windows.go
  pkg/deviceutils/fake-device-utils.go
  pkg/gce-pd-csi-driver/node.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1748 Add CHANGELOG-1.14 for v1.14.0
  CHANGELOG/CHANGELOG-1.14.md
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none, lifecycle/rotten

#1841 Update logic to use SI for VACs
  deploy/kubernetes/overlays/dev/driver-args.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  examples/kubernetes/demo-vol-create.yaml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, kind/cleanup, ok-to-test
