Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-12, with the labels that each got.

#1876 Refactor metric defer() statements to gRPC metric interceptor
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/server.go
  pkg/gce-pd-csi-driver/server_test.go
  pkg/metrics/interceptor.go
  pkg/metrics/metadata.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/metrics_test_util.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, kind/cleanup, size/XL

#1883 Don't overwrite libc in distroless debian base image
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1888 update prow rc with 1.15.3-rc1 release candidate
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1875 Require VACs to use SI units
  examples/kubernetes/demo-vol-create.yaml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S, kind/cleanup, ok-to-test

#1889 Make the volume attribute class file a configurable input in the tester script
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1891 Skip xfs test for GCE test skip
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1892 Automated cherry pick of #1875: Require VACs to use SI units
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#1893 create new rc for 1.15.3
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, release-note-none
