Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#1689 Remove device disable call
  pkg/deviceutils/device-utils_linux.go
  pkg/gce-pd-csi-driver/node.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S

#1695 Remove unused DisableDevice method
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_linux.go
  pkg/gce-pd-csi-driver/node.go
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none

#1696 Use instances.list to determine PublishedNodeIds in ListVolume API
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/e2e/utils/utils.go
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XL

#1711 Add data caching feature with Local SSDs for PD
  Dockerfile
  cmd/gce-pd-csi-driver/main.go
  deploy/kubernetes/base/node_linux/node.yaml
  pkg/common/constants.go
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/runcmd.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/config/data-cache-sc.yaml
  test/remote/client-wrappers.go
  test/remote/instance.go
  test/remote/setup-teardown.go
  test/run-e2e-local.sh
  test/sanity/sanity_test.go
  vendor/k8s.io/mount-utils/mount_linux.go
Labels: cncf-cla: yes, size/XXL, release-note

#1719 Add separate flags for node and controller and hash nodeId
  Dockerfile
  cmd/gce-pd-csi-driver/main.go
  pkg/common/utils.go
  pkg/gce-pd-csi-driver/cache.go
  test/e2e/utils/utils.go
  test/run-e2e-local.sh
Labels: cncf-cla: yes, approved, size/M, release-note-none

#1710 Reassign error returned from validateStoragePools so InvalidArgument is recorded
  pkg/gce-pd-csi-driver/controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1720 Return Unavailable for 'connection reset by peer' errors
  pkg/common/utils.go
  pkg/common/utils_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S, kind/cleanup

#1718 Improve error messages for ControllerExpandVolume / CreateSnapshot of multi-zone PV.
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#1708 Properly unwrap gce-compute error code.
  pkg/common/utils.go
  pkg/common/utils_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#1728 Install golang version inside run-k8s-integration-ci.sh script run by prow tests
  test/run-k8s-integration-ci.sh
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none
