Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#1660 Add link to Hyperdisk documentation for provisioned-throughput-on-create
  README.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/XS, release-note-none

#1666 Migrate Hyperdisk/CHD/StoragePools to GCE v1 disk API
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, kind/cleanup

#1667 Remove support for GCE Alpha Disk Insert API
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/cloud-disk_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/metrics/metrics_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, kind/cleanup

#1670 Change k8s version from stable->latest to pick up new COS image
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1664 Record original error code to operation_errors metric for temporary errors
  pkg/common/errors.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, kind/cleanup

#1673 Remove short variable declaration from validateStoragePools
  pkg/gce-pd-csi-driver/controller.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS

#1656 Update isVolumePathMounted log message
  pkg/gce-pd-csi-driver/node.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1658 Add support for checking if a device is being used by a filesystem
  pkg/deviceutils/device-utils.go
  pkg/deviceutils/device-utils_linux.go
  pkg/deviceutils/device-utils_windows.go
  pkg/deviceutils/fake-device-utils.go
  pkg/gce-pd-csi-driver/node.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#1683 Fix CVE-2023-45288
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test

#1692 Fix e2e tests to run on cloudtop
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/instance.go
  test/remote/setup-teardown.go
  test/run-e2e-local.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none
