Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#1604 Cherry-pick #1558 to release-1.8
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, release-note-none

#1606 Map UNSUPPORTED_OPERATION GCE operation error codes to InvalidArgument
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce-compute_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#1605 Changelog updates
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/M, release-note-none

#1586 Update driver to support compute staging
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1593 Add support for a multi-zone volumeHandle
  cmd/gce-pd-csi-driver/main.go
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/cloud-disk_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/remote/client-wrappers.go
  test/sanity/sanity_test.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note

#1609 fix pointer issue for GCE staging support
  cmd/gce-pd-csi-driver/main.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1614 Automated cherry pick of #1586: update driver to support staging compute #1609: fix pointer issue for GCE staging support
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1615 Revert "Automated cherry pick of #1586: update driver to support staging compute#1609: fix pointer issue for GCE staging support"
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1617 Automated cherry pick of #1586: update driver to support staging compute #1609: fix pointer issue for GCE staging support
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1616 Automated cherry pick of #1593: Add support for a multi-zone volumeHandle
  cmd/gce-pd-csi-driver/main.go
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/cloud-disk_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/remote/client-wrappers.go
  test/sanity/sanity_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1618 Add changelog for 1.13.1
  CHANGELOG/CHANGELOG-1.13.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/S, release-note-none

#1619 Update stable-master with v1.13.1
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1620 Fix error when no compute endpoint is passed
  cmd/gce-pd-csi-driver/main.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none

#1623 Add 1.13.2 Changelog, update rc image
  CHANGELOG/CHANGELOG-1.13.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none

#1624 release-1.13 cut details for 1.13.2
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none
