Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-06, with the labels that each got.

#1730 Improve enum and string list flag parse handling
  cmd/gce-pd-csi-driver/main.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M, kind/cleanup

#1694 Update debian image from bullseye to bookworm to fix CVEs
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#1732 Improvements to e2e test suite runner
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none, kind/test

#1736 Update docker file to get lvm configuration
  Dockerfile
  initialize-driver.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none, ok-to-test

#1733 Add support for "multi-zone" volume handle provisioning and deletion
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/cloud-disk_test.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-cloud-provider/compute/gce_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, release-note

#1745 prune changelog for 1.14
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, size/XXL, kind/documentation, approved, release-note-none

#1746 Add back CHANGELOG, removed in #1745 by mistake
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, size/XXL, kind/documentation, approved, release-note-none

#1747 prune changelog for 1.14
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, size/XXL, kind/documentation, approved, release-note-none

#1760 Adding missing libgpg-error.so.0 required by nvme-cli
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#1761 Format byte array error output from google_nvme_id as string
  pkg/deviceutils/device-utils.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/XS, kind/cleanup

#1772 Reverting the Dockerfile debian image from bookworm to bullseye due to regression
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M
