Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#1817 Add manual deployment instructions for Storage Pools
  docs/kubernetes/user-guides/storage-pools.md
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/M, release-note-none

#1823 Fix cachesize parsing and setup logic
  cmd/gce-pd-csi-driver/main.go
  pkg/common/constants.go
  pkg/common/parameters.go
  pkg/gce-pd-csi-driver/cache.go
  test/e2e/utils/utils.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1801 Add ControllerModifyVolume functionality
  cmd/gce-pd-csi-driver/main.go
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  deploy/kubernetes/overlays/dev/controller_always_pull.yaml
  deploy/kubernetes/overlays/dev/driver-args.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  examples/kubernetes/demo-vol-update.yml
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  test/k8s-integration/cluster.go
  test/k8s-integration/config/hdb-volumeattributesclass.yaml
  test/k8s-integration/config/sc-hdb.yaml
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
  test/k8s-integration/main.go
  test/remote/client-wrappers.go
  test/run-k8s-integration.sh
  test/sanity/sanity_test.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, release-note, ok-to-test

#1827 Update prow stable rc master image to v1.15.0-rc1
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1829 Upgrade latest stable image from v1.13.2 to v1.15.0
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none, ok-to-test

#1832 Update base image to bookworm-v1.0.4-gke.2
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1836 Create documentation for ControllerModifyVolume and controller default
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  docs/kubernetes/user-guides/controller-modify-volume.md
  examples/kubernetes/demo-vol-create.yaml
  examples/kubernetes/demo-vol-update.yaml
  examples/kubernetes/demo-vol-update.yml
  test/run-k8s-integration-ci.sh
Labels: size/L, cncf-cla: yes, lgtm, kind/documentation, approved, release-note-none, ok-to-test

#1840 Automated cherry pick of #1708: Properly unwrap gce-compute error code.
  pkg/common/errors.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1839 [release-1.13] Properly unwrap gce-compute error code.
  pkg/common/utils.go
  pkg/common/utils_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1838 Enable VolumeAttributesClass feature gate for CI runs
  deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/driver-args.yaml
  deploy/kubernetes/overlays/prow-stable-sidecar-rc-master/kustomization.yaml
  docs/kubernetes/user-guides/volume-attributes-class.md
  test/run-k8s-integration-ci.sh
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S, release-note-none, ok-to-test
