Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2025-06, with the labels that each got.

#2105 Add Gen4 Lssd VM Test
  pkg/gce-pd-csi-driver/node_test.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#2108 [release-1.17] Add Labels Override for Gen3/Gen4 VMs
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/M

#2113 Release 1.20 cut details for v1.20.0
  README.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test
