Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#1915 Add support for HdHA disk provisioning
  cmd/gce-pd-csi-driver/main.go
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/utils_test.go
  pkg/gce-cloud-provider/compute/cloud-disk.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/run-e2e.sh
  test/sanity/sanity_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/XL, ok-to-test

#1914 Add XMLName back to TestSuite struct
  test/k8s-integration/filter-junit.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1918 Force timeout nodeunstagevolume
  cmd/gce-pd-csi-driver/main.go
  go.mod
  go.sum
  pkg/gce-pd-csi-driver/device_error_map.go
  pkg/gce-pd-csi-driver/device_error_map_test.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/sanity/sanity_test.go
  vendor/github.com/hashicorp/golang-lru/v2/LICENSE
  vendor/github.com/hashicorp/golang-lru/v2/expirable/expirable_lru.go
  vendor/github.com/hashicorp/golang-lru/v2/internal/list.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, kind/design, release-note-none, ok-to-test

#1926 Update RC image for 1.16.
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#1927 Copy kubernetes test binaries to _rundir, instead of _artifacts when running integration test on k8s master branch
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none

#1919 Feature: Changes to support Hyperdisk Multi-Writer mode by moving to Beta APIs.
  pkg/common/parameters.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#1938 Remove VAC name from Driver name
  test/k8s-integration/config/test-config-template.in
  test/k8s-integration/driver-config.go
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none

#1857 switch to use snapshots.insert instead of disks.createsnapshot
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
  pkg/gce-cloud-provider/compute/gce-compute.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, lifecycle/stale, release-note, size/M

#1932 Add support for data cache
  Dockerfile
  cmd/gce-pd-csi-driver/main.go
  deploy/kubernetes/base/controller/cluster_setup.yaml
  deploy/kubernetes/base/node_linux/node.yaml
  initialize-driver.sh
  pkg/common/constants.go
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/common/runcmd.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/deviceutils/device-utils.go
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/gce-pd-driver_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/config/data-cache-sc.yaml
  test/remote/client-wrappers.go
  test/remote/instance.go
  test/remote/setup-teardown.go
  test/run-e2e.sh
  test/sanity/sanity_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note-none

#1945 Derive access mode from the CreateVolume request instead of parameters
  pkg/common/constants.go
  pkg/common/parameters.go
  pkg/common/utils.go
  pkg/gce-cloud-provider/compute/fake-gce.go
  pkg/gce-cloud-provider/compute/gce-compute.go
  pkg/gce-cloud-provider/compute/gce-compute_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  pkg/gce-pd-csi-driver/utils.go
  pkg/gce-pd-csi-driver/utils_test.go
  test/e2e/tests/multi_zone_e2e_test.go
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/testing/protocmp/reflect.go
  vendor/google.golang.org/protobuf/testing/protocmp/util.go
  vendor/google.golang.org/protobuf/testing/protocmp/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note-none, ok-to-test

#1950 Update RAID logic and post-RAID validation to integrate Datacache support for GKE nodes
  cmd/gce-pd-csi-driver/main.go
  pkg/common/constants.go
  pkg/common/runcmd.go
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/node.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/utils/utils.go
  test/remote/client-wrappers.go
  test/remote/instance.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#1956 Bump base image version to bookworm-v1.0.4-gke.3
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/XS, release-note-none

#1957 Bump base image version to bookworm-v1.0.4-gke.3
  Dockerfile
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S

#1958 Bump base image version to bookworm-v1.0.4-gke.3
  Dockerfile
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S

#1954 Fix chunksize bug for large cache size in data cache
  deploy/kubernetes/base/controller/controller.yaml
  pkg/common/parameters.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/cache_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1946 Implementing watcher & reboot stability for data cache to master branch.
  cmd/gce-pd-csi-driver/main.go
  go.mod
  go.sum
  pkg/gce-pd-csi-driver/cache.go
  vendor/github.com/fsnotify/fsnotify/.cirrus.yml
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/backend_fen.go
  vendor/github.com/fsnotify/fsnotify/backend_inotify.go
  vendor/github.com/fsnotify/fsnotify/backend_kqueue.go
  vendor/github.com/fsnotify/fsnotify/backend_other.go
  vendor/github.com/fsnotify/fsnotify/backend_windows.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/internal/darwin.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_darwin.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_dragonfly.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_freebsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_kqueue.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_linux.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_netbsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_openbsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_solaris.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_windows.go
  vendor/github.com/fsnotify/fsnotify/internal/freebsd.go
  vendor/github.com/fsnotify/fsnotify/internal/internal.go
  vendor/github.com/fsnotify/fsnotify/internal/unix.go
  vendor/github.com/fsnotify/fsnotify/internal/unix2.go
  vendor/github.com/fsnotify/fsnotify/internal/windows.go
  vendor/github.com/fsnotify/fsnotify/system_bsd.go
  vendor/github.com/fsnotify/fsnotify/system_darwin.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test
