Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#2071 Bump up golang.org version to 0.39
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test

#2073 Bump golang.org version to 0.39 to fix CVE-2025-22872
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: kind/bug, cncf-cla: yes, lgtm, size/XXL, approved, release-note, ok-to-test

#2074 Remove no-op log statement in reduceVolumeGroup for release 1.18 branch.
  pkg/gce-pd-csi-driver/cache.go
Labels: cncf-cla: yes, lgtm, approved, size/XS, release-note-none, ok-to-test

#2072 Adjust Attach Limits for Gen3 Machines + Add Labels Override
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note

#2075 Update OWNERS to include juliankatz
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup, release-note-none

#2078 Update 1.17 changelog based on Releases page, make placeholder 1.18
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
Labels: cncf-cla: yes, lgtm, approved, size/M, kind/cleanup, release-note-none

#2076 Remove per-branch changelogs, reference master version
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, lgtm, size/XXL, approved, kind/cleanup, release-note-none

#2082 Upgrade to resizer to v1.13.0
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none, ok-to-test

#2091 btrfs recalim on kernel v5.19+: use bg_reclaim_threshold
  README.md
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/gce-pd-driver.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
  pkg/gce-pd-csi-driver/utils.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#2092 Using Default PD Attach Limit for Gen3 Machines
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, approved, release-note

#2084 Upgrade images
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none, ok-to-test

#2096 Fix Gen4 Custom VM Cases
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M

#2089 Only add disk support topologies if StorageClass parameter is true
  README.md
  cmd/gce-pd-csi-driver/main.go
  pkg/common/parameters.go
  pkg/common/parameters_test.go
  pkg/gce-pd-csi-driver/controller.go
  pkg/gce-pd-csi-driver/controller_test.go
  test/e2e/tests/single_zone_e2e_test.go
  test/e2e/utils/utils.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note, ok-to-test

#2103 prune changelog for 1.19 release
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/CHANGELOG-1.18.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: cncf-cla: yes, lgtm, size/XXL, approved, release-note-none
