Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#1966 Adding additional checks for data cache watcher and reduceVolumeGroup
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/cache.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#1953 Fix build issues for Windows image.
  Makefile
  go.mod
  go.sum
  manifest_osversion.sh
  test/run-windows-k8s-integration.sh
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none

#1971 Update changelog and test image to release-v1.17.1
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.6.md
  CHANGELOG/CHANGELOG-0.7.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/CHANGELOG-1.11.md
  CHANGELOG/CHANGELOG-1.12.md
  CHANGELOG/CHANGELOG-1.13.md
  CHANGELOG/CHANGELOG-1.14.md
  CHANGELOG/CHANGELOG-1.15.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: lgtm, size/XXL, cncf-cla: no, kind/documentation, approved, release-note-none

#1989 Pass performance parameters when creating regional disks.
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/multi_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note-none

#1973 Update change log and docs for release v1.17.1 to master
  CHANGELOG/CHANGELOG-1.17.md
  CHANGELOG/README.md
  README.md
  deploy/kubernetes/base/controller/controller.yaml
  deploy/kubernetes/base/node_linux/node.yaml
  deploy/kubernetes/base/node_windows/node.yaml
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: cncf-cla: yes, lgtm, kind/documentation, approved, size/M, release-note-none

#1993 Fix logic bug while checking available LSSDs for RAIDing for Data Cache
  cmd/gce-pd-csi-driver/main.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S

#1990 Add exponential backoff retries for getting Node from API server logic
  cmd/gce-pd-csi-driver/main.go
  pkg/gce-pd-csi-driver/cache.go
  test/e2e/utils/utils.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/M, ok-to-test

#1910 Add handling for TPC to GetRegionFromZones
  pkg/common/utils.go
  pkg/common/utils_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, release-note-none, ok-to-test

#1997 update debian image to fix CVE
  Dockerfile
  Dockerfile.debug
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/XS

#2010 Map insufficient free space error during cache creating to InvalidArgument error
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/node.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S

#2007 Fix units for cache size while calculating chunk size for LVM
  pkg/gce-pd-csi-driver/cache.go
  pkg/gce-pd-csi-driver/cache_test.go
  test/remote/client-wrappers.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/S

#2001 feat: enable btrfs
  Dockerfile
  README.md
Labels: kind/feature, cncf-cla: yes, lgtm, approved, release-note, size/S, ok-to-test

#2004 Add pageToken response check to ListSnapshots gRPC API
  pkg/gce-cloud-provider/compute/gce-compute.go
  test/e2e/tests/single_zone_e2e_test.go
  test/remote/client-wrappers.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, release-note, size/S

#2019 Add Attach Limit for Hyperdisk + Gen4 VMs
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/gce-pd-csi-driver/node.go
  pkg/gce-pd-csi-driver/node_test.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1999 Make integration tests support windows 2022
  Makefile
  test/k8s-integration/cluster.go
  test/k8s-integration/driver.go
  test/k8s-integration/main.go
  test/run-windows-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/M, release-note-none

#2024 Bump csi proxy client version to 1.2.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none, ok-to-test

#2017 Increase csi-snapshotter requeue interval --retry-interval-max=60s for deployed overlay
  deploy/kubernetes/base/controller/controller.yaml
Labels: cncf-cla: yes, lgtm, approved, kind/failing-test, size/XS, release-note-none
