Repository kubernetes-sigs/gcp-compute-persistent-disk-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#1902 fix VAC tests now that VAC file is always set
  test/k8s-integration/main.go
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/failing-test, release-note-none

#1903 1.15.4 CHANGELOG, update rc image
  CHANGELOG/CHANGELOG-1.15.md
  deploy/kubernetes/images/prow-stable-sidecar-rc-master/image.yaml
Labels: kind/feature, cncf-cla: yes, lgtm, approved, size/S, release-note-none

#1908 experimental fix, remove deviceInUse check
  pkg/gce-pd-csi-driver/node.go
Labels: cncf-cla: yes, lgtm, approved, release-note, size/M

#1909 [exp] remove e2e test for in use check, this is to make sure that the rest of the tests are running
  test/e2e/tests/single_zone_e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, approved, release-note

#1911 Update kubetest2 version
  test/k8s-integration/filter-junit.go
  test/run-k8s-integration-ci.sh
  test/run-k8s-integration-migration.sh
  test/run-k8s-integration.sh
Labels: cncf-cla: yes, lgtm, approved, size/S, kind/cleanup, release-note-none
